### ISSUE TITLE
Deserialize Absent Values

### ISSUE THREAD

**Issue by Sparky983** [Sparky983/warp-config#70]
## Description

This change would change `Deserializer::deserialize` to be take in a `null` `ConfigurationNode` in the case it was absent.

```java
public interface Deserializer<T> {
  /**
   * ...
   * @param node the node, or {@code null} indicating the value was absent
   * from the configuration
   * ...
   */
  Renderer<T> deserialize(@Nullable ConfigurationNode node, Context context)
      throws DeserializationException;

  // ...
}
```

## Implementation

Aside from the addition of this feature to the API, some internal code should be refactored to use this API instead of internal APIs (`DefaultsRegistry`).

The configuration deserializer will give nested errors. To display this, here's an example:

```java
@Configuration
public interface TestConfiguration {
  @Property("nested")
  Nested nested1();

  @Configuration
  interface Nested {
    @Property("property-1")
    String property1();

    @Property("property-2")
    String property2();
  }
}
```

and the error message, given a blank configuration, before and after that change:

```yaml
# before
 - nested:
   - Must be set to a value

# after
 - nested:
   - property-1:
     - Must be set to a value
   - property-2:
     - Must be set to a value
``` 

Additionally, defaults, which are external to deserializers, would no longer be necessary as defaults could be implemented inside of deserializers. 

## Motivation

There main motivation for this change is that it gives more control to deserializers. The main use cases I see are:
- Customised absence errors
- Ability to implement defaults for absent values
